import localFont from "next/font/local";
import "./globals.css";
import App from "@/app/app";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const domaineBlack = localFont({
  src: "./fonts/domaine/DomaineDispNar-Semibold.otf",
  variable: "--domaine-black",
  weight: "100 900",
});


const dancing = localFont({
  src: "./fonts/dancing/DancingScript-Regular.ttf",
  variable: "--dancing-regular",
  weight: "100 900",
});

const lexend = localFont({
  src: "./fonts/lexend/Lexend-Light.ttf",
  variable: "--lexend-light",
  weight: "100 900",
});

export const metadata = {
  title: "Dapur Gandi",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body
        className={`${domaineBlack.variable} ${dancing.variable} ${lexend.variable} `}
      >
        {children}
      </body>
    </html>
  );
}
